//Calling the inquirer module
const inquirer = require('inquirer');
//Calling the jest module
const jest = require('jest');
//Calling the fs module
const fs = require('fs');
//Calling the employee js
const employee = require('./tests/employee.test.js')
//Calling the engineer js
const engineer = require('./tests/engineer.test.js')
//Calling the intern js
const intern = require('./tests/intern.test.js')
//Calling the manager js
const manager = require('./tests/manager.test.js')